version: "3.1"
services:
  fox-local:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fox-local
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="Europe/London"
    ports:
      - 10001:10001
    restart: unless-stopped
